backend:
  name: git-gateway
  branch: main

media_folder: "assets/art"
public_folder: "assets/art"

collections:
  - name: "content"
    label: "Quản lý Nội dung"
    delete: false # Tránh xóa nhầm file data.json
    files:
      - label: "Danh sách Tranh vẽ"
        name: "arts"
        file: "data.json"
        fields:
          - name: artData
            label: "Tất cả tranh"
            widget: "object"
            fields:
              - label: "Thêm/Sửa Tranh"
                name: "items"
                widget: "list"
                allow_add: true
                summary: "{{title}}"
                fields:
                  - {label: "ID (Ví dụ: tranh1)", name: "id", widget: "string"}
                  - {label: "Tiêu đề", name: "title", widget: "string"}
                  - {label: "Ảnh", name: "image", widget: "image"}
                  - {label: "Mô tả", name: "description", widget: "text"}
                  - {label: "Ngày (YYYY-MM-DD)", name: "date", widget: "datetime", format: "YYYY-MM-DD"}
                  - {label: "Link Toyhouse", name: "link", widget: "string", required: false}

      - label: "Danh sách Video"
        name: "videos"
        file: "data.json"
        fields:
          - name: videoData
            label: "Tất cả Video"
            widget: "list"
            summary: "{{title}}"
            fields:
              - {label: "Tiêu đề", name: "title", widget: "string"}
              - {label: "Link Embed Youtube", name: "embedUrl", widget: "string"}
              - {label: "Mô tả", name: "description", widget: "string"}